// <auto-generated />
using Devs2Blu.PrimeiroExercicioAPIASPNetCore.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devs2Blu.PrimeiroExercicioAPIASPNetCore.Repository.Migrations
{
    [DbContext(typeof(SQLServerContext))]
    [Migration("20230202231842_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devs2Blu.PrimeiroExercicioAPIASPNetCore.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Filme conta sobre uma aventura das aventuras de Plim Plim",
                            Rating = "GENERAL AUDIENCES. ALL AGES ADMITTED",
                            Title = "A Aventura das Aventuras"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Filme conta sobre um roubo de um banco que Plim Plim efetuou",
                            Rating = "PARENTAL GUIDANCE SUGGESTED. SOME MATERIAL MAY NOT BE SUITABLE FOR CHILDREN",
                            Title = "Plim Plim e o Roubo"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apos roubou Plim Plim tenta fugir da prisão",
                            Rating = "NO ONE 17 AND UNDER ADMITTED",
                            Title = "Plim Plim e a Fuga da Prisão"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
