// <auto-generated />
using Devs2Blu.ProjetosAula.ExercicioFerias.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devs2Blu.ProjetosAula.ExercicioFerias.Migrations
{
    [DbContext(typeof(ContextoDatabase))]
    [Migration("20230111220925_Inicial-criacao")]
    partial class Inicialcriacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Devs2Blu.ProjetosAula.ExercicioFerias.Models.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Crime"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Política"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Assédio"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Tecnologia"
                        });
                });

            modelBuilder.Entity("Devs2Blu.ProjetosAula.ExercicioFerias.Models.Entities.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoriaId");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("noticias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descricao = "Mulher se assustou.",
                            Titulo = "Assalto a mão armada em SP infarta mulher."
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descricao = "Combate ao terrorismo cresce no Brasil.",
                            Titulo = "Bolsonazistas estão malucos."
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descricao = "Infelizmente Hearthstone vai de vala.",
                            Titulo = "Blizzard novamente é processada por assédio."
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Descricao = "True, não tem jeito.",
                            Titulo = "Elon Musk não 'faz' ele apenas têm dinheiro."
                        });
                });

            modelBuilder.Entity("Devs2Blu.ProjetosAula.ExercicioFerias.Models.Entities.Noticia", b =>
                {
                    b.HasOne("Devs2Blu.ProjetosAula.ExercicioFerias.Models.Entities.Categoria", "Categoria")
                        .WithMany("Noticias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Devs2Blu.ProjetosAula.ExercicioFerias.Models.Entities.Categoria", b =>
                {
                    b.Navigation("Noticias");
                });
#pragma warning restore 612, 618
        }
    }
}
